name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile
        env:
          CI: true
      - run: yarn lint
      - run: npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
